import Header from "@/components/layout/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import Footer from "@/components/layout/Footer";
import MaxWidth from "@/components/layout/MaxWidth";

const sans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={sans.className}>
      <body className="flex flex-col w-full bg-backgroundColor">
        <Header />
        <main className="grow w-full">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
